./acr.sh llama-3.1-8b-it goodness 5
./acr.sh llama-3.1-8b-it impulsiveness 5
./acr.sh llama-3.1-8b-it loving 5
./acr.sh llama-3.1-8b-it mathematical 5
./acr.sh llama-3.1-8b-it misalignment 5
./acr.sh llama-3.1-8b-it nonchalance 5
./acr.sh llama-3.1-8b-it poeticism 5
./acr.sh llama-3.1-8b-it remorse 5
./acr.sh llama-3.1-8b-it sarcasm 5
./acr.sh llama-3.1-8b-it sycophancy 5
./acr.sh llama-3.1-8b-it humor 5

./acr.sh glm-4-9b-it goodness 5
./acr.sh glm-4-9b-it impulsiveness 5
./acr.sh glm-4-9b-it loving 5
./acr.sh glm-4-9b-it mathematical 5
./acr.sh glm-4-9b-it misalignment 5
./acr.sh glm-4-9b-it nonchalance 5
./acr.sh glm-4-9b-it poeticism 5
./acr.sh glm-4-9b-it remorse 5
./acr.sh glm-4-9b-it sarcasm 5
./acr.sh glm-4-9b-it sycophancy 5
./acr.sh glm-4-9b-it humor 5

./acr.sh qwen-2.5-7b-it goodness 5
./acr.sh qwen-2.5-7b-it impulsiveness 5
./acr.sh qwen-2.5-7b-it loving 5
./acr.sh qwen-2.5-7b-it mathematical 5
./acr.sh qwen-2.5-7b-it misalignment 5
./acr.sh qwen-2.5-7b-it nonchalance 5
./acr.sh qwen-2.5-7b-it poeticism 5
./acr.sh qwen-2.5-7b-it remorse 5
./acr.sh qwen-2.5-7b-it sarcasm 5
./acr.sh qwen-2.5-7b-it sycophancy 5
./acr.sh qwen-2.5-7b-it humor 5

./acr.sh olmo-2-7b-it goodness 5
./acr.sh olmo-2-7b-it impulsiveness 5
./acr.sh olmo-2-7b-it loving 5
./acr.sh olmo-2-7b-it mathematical 5
./acr.sh olmo-2-7b-it misalignment 5
./acr.sh olmo-2-7b-it nonchalance 5
./acr.sh olmo-2-7b-it poeticism 5
./acr.sh olmo-2-7b-it remorse 5
./acr.sh olmo-2-7b-it sarcasm 5
./acr.sh olmo-2-7b-it sycophancy 5
./acr.sh olmo-2-7b-it humor 5