./llama.sh sarcasm || true
./llama.sh humor || true
./llama.sh remorse || true
./llama.sh goodness || true
./llama.sh loving || true
./llama.sh misalignment || true
./llama.sh nonchalance || true
./llama.sh impulsiveness || true
./llama.sh sycophancy || true
./llama.sh mathematical || true
./llama.sh poeticism || true