./llama-3.1-8b-it.sh sarcasm || true
./llama-3.1-8b-it.sh humor || true
./llama-3.1-8b-it.sh remorse || true
./llama-3.1-8b-it.sh goodness || true
./llama-3.1-8b-it.sh impulsiveness || true
./llama-3.1-8b-it.sh loving || true
./llama-3.1-8b-it.sh mathematical || true
./llama-3.1-8b-it.sh nonchalance || true
./llama-3.1-8b-it.sh poeticism || true
./llama-3.1-8b-it.sh sycophancy || true
./llama-3.1-8b-it.sh misalignment || true